/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '0. CPU 이론',
      items: [{ type: 'autogenerated', dirName: '0-cpu-theory' }],
      customProps: { thumbnail: '/img/thumbnails/cpu.png' },
    },
    {
      type: 'category',
      label: '1. 프로그래밍 기초',
      items: [{ type: 'autogenerated', dirName: '1-programming-basics' }],
      customProps: { thumbnail: '/img/thumbnails/programming.png' },
    },
    {
      type: 'category',
      label: '2. C언어 심화',
      items: [{ type: 'autogenerated', dirName: '2-c-language' }],
      customProps: { thumbnail: '/img/thumbnails/c-language.png' },
    },
    {
      type: 'category',
      label: '3. 파이썬 심화',
      items: [{ type: 'autogenerated', dirName: '3-python' }],
      customProps: { thumbnail: '/img/thumbnails/python.png' },
    },
    {
      type: 'category',
      label: '4. 장고, DB',
      items: [{ type: 'autogenerated', dirName: '4-django-db' }],
      customProps: { thumbnail: '/img/thumbnails/django.png' },
    },
    {
      type: 'category',
      label: '5. 데이터베이스',
      items: [{ type: 'autogenerated', dirName: '5-database' }],
      customProps: { thumbnail: '/img/thumbnails/database.png' },
    },
    {
      type: 'category',
      label: '6. 네트워크',
      items: [{ type: 'autogenerated', dirName: '6-network' }],
      customProps: { thumbnail: '/img/thumbnails/network.png' },
    },
    {
      type: 'category',
      label: 'Tiny Projects',
      items: [{ type: 'autogenerated', dirName: '7-tiny-projects' }],
      customProps: { thumbnail: '/img/thumbnails/projects.png' },
    },
    {
      type: 'category',
      label: '7. 컴퓨터 구조',
      items: [{ type: 'autogenerated', dirName: '8-architecture' }],
      customProps: { thumbnail: '/img/thumbnails/architecture.png' },
    },
    {
      type: 'category',
      label: '8. 운영체제',
      items: [{ type: 'autogenerated', dirName: '9-os' }],
      customProps: { thumbnail: '/img/thumbnails/os.png' },
    },
    {
      type: 'category',
      label: '9. OOP',
      items: [{ type: 'autogenerated', dirName: '10-oop' }],
      customProps: { thumbnail: '/img/thumbnails/oop.png' },
    },
    {
      type: 'category',
      label: '10. ML',
      items: [{ type: 'autogenerated', dirName: '11-ml' }],
      customProps: { thumbnail: '/img/thumbnails/ml.png' },
    },
    {
      type: 'category',
      label: '추가 자료',
      items: [{ type: 'autogenerated', dirName: '12-extras' }],
      customProps: { thumbnail: '/img/thumbnails/extras.png' },
    },
  ],
};

module.exports = sidebars;
