/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '0. CPU 이론',
      items: [{ type: 'autogenerated', dirName: '0-cpu-theory' }],
      customProps: { emoji: '🖥️' },
    },
    {
      type: 'category',
      label: '1. 프로그래밍 기초',
      items: [{ type: 'autogenerated', dirName: '1-programming-basics' }],
      customProps: { emoji: '👨‍💻' },
    },
    {
      type: 'category',
      label: '2. C언어 심화',
      items: [{ type: 'autogenerated', dirName: '2-c-language' }],
      customProps: { emoji: '⚙️' },
    },
    {
      type: 'category',
      label: '3. 파이썬 심화',
      items: [{ type: 'autogenerated', dirName: '3-python' }],
      customProps: { emoji: '🐍' },
    },
    {
      type: 'category',
      label: '4. 장고, DB',
      items: [{ type: 'autogenerated', dirName: '4-django-db' }],
      customProps: { emoji: '🌐' },
    },
    {
      type: 'category',
      label: '5. 데이터베이스',
      items: [{ type: 'autogenerated', dirName: '5-database' }],
      customProps: { emoji: '🗄️' },
    },
    {
      type: 'category',
      label: '6. 네트워크',
      items: [{ type: 'autogenerated', dirName: '6-network' }],
      customProps: { emoji: '🌍' },
    },
    {
      type: 'category',
      label: '7. Tiny Projects',
      items: [{ type: 'autogenerated', dirName: '7-tiny-projects' }],
      customProps: { emoji: '💡' },
    },
    {
      type: 'category',
      label: '8. 컴퓨터 구조',
      items: [{ type: 'autogenerated', dirName: '8-architecture' }],
      customProps: { emoji: '🔧' },
    },
    {
      type: 'category',
      label: '9. 운영체제',
      items: [{ type: 'autogenerated', dirName: '9-os' }],
      customProps: { emoji: '⚡' },
    },
    {
      type: 'category',
      label: '10. OOP',
      items: [{ type: 'autogenerated', dirName: '10-oop' }],
      customProps: { emoji: '🧱' },
    },
    {
      type: 'category',
      label: '11. ML',
      items: [{ type: 'autogenerated', dirName: '11-ml' }],
      customProps: { emoji: '🤖' },
    },
    {
      type: 'category',
      label: '추가 자료',
      items: [{ type: 'autogenerated', dirName: '12-extras' }],
      customProps: { emoji: '📚' },
    },
  ],
};

module.exports = sidebars;
